---
name: Tests

on:
  pull_request:
    branches:
      - main

jobs:
  generate-matrix:
    name: Generate matrix
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.generate-matrix.outputs.matrix }}
    steps:
      - name: Generate matrix
        id: generate-matrix
        uses: wandnz/action-supported-distro-releases@v1

  molecule:
    name: Molecule (ansible:${{ matrix.ansible.core }}, ${{ matrix.target }})
    runs-on: ubuntu-latest
    needs: generate-matrix
    strategy:
      fail-fast: false
      matrix:
        target: ${{ fromJson(needs.generate-matrix.outputs.matrix) }}
        ansible:
          - core: "2.17"
            community: "10.0"
            python: "3.12"
          - core: "latest"
            community: "latest"
            python: "3.x"
    steps:
      - name: Checkout repo
        uses: actions/checkout@v5
      - name: Setup python
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.ansible.python }}
      - name: Setup ansible
        run: |
          if [ "${{ matrix.ansible.community }}" == "latest" ]; then
            pip3 install ansible
          else
            pip3 install ansible~=${{ matrix.ansible.community }}
          fi
      - name: Install test dependencies
        run: pip3 install -r test-requirements.txt
      - name: Run molecule
        run: molecule test
        env:
          MOLECULE_DOCKER_IMAGE: ${{ matrix.target }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
